#Browser

browser = Chrome




#URL
url = https://test-ozone.infinitisoftware.net/



#Failed_Script_Rerun
#rerun = true


#Corporate admint Credentials
CAusername = selvacorporate8@yopmail.com
CApassword = Infi@123


#Corporate user Credentials
CUAdminusername = selvauser10@yopmail.com
CUAdminpassword = Infi@123



#Approve user Credentials
ApproveAdminusername = selvauser10@yopmail.com
ApproveAdminpassword = Infi@123